[simulation]
num_of_rounds = 1 # Number of runs of the simulation, statistics will be averaged over all runs, rounds run concurrently
num_of_agents = 1 # They work concurrently

[logging]
enabled = false # Enable logging
print_interval = 30 # Print statistics every print_interval seconds for each simulation round, print is enabled anyway even if logging is disabled

[network]
# You can use an exact number to reproduce the psoudo random results
seed = 1677085608
# All topologies will be connected with no self-loops
# ["random", "path", "star", "complete", "balanced_tree"]
# IDEA: add reading network topology from a file
topology = "2d_grid"
nodes_num = 9
channels_num = 0 # For "path", "star", "grid", "complete", "balanced_tree" topologies, the number of channels will be ignored
sats_min = 3 # Minimum amount of satoshies in each side of the channel
sats_max = 3 # Maximum amount of satoshies in each side of the channel
saturation_probability = 0 # The probability of a channel being saturated,range [0,1]
reopen_enabled = true # Reopen closed channels 50-50, # TODO: Reopens channels of the first route tried, maybe not the best idea, but it is kinda similar to reality
count_initial_channels_as_reopens = true # Count initial channels as reopens, set this to false if you don't want to count initial channels as reopens
delay_enabled = false # Enable network delays
rtt_delay = 0 # Delay in milliseconds for each RTT
delay_randomness_threshold = 0 # Delay randomness threshold, 0.3 means that the delay will be between 0.7 * rtt_delay and 1.3 * rtt_delay
query_rtts = 0 # Number of RTTs for a query
tx_hop_rtts = 0 # Number of RTTs for a transaction to proceed through a single hop

[agents]
seed = 1677085608
check_source_balance = false # Only choose source nodes with enough balance, set this to false only if reopening is enabled
num_of_transactions = 100000 # Total number of transactions a single agent will make. will be treated as max_num_of_transactions if method is "until_failure".
src_dst = "big_to_small" # ["fixed_pairs", "random", "big_to_small"] # TODO: add "fixed_pairs" option
tx_rest = 0 # Delay between transactions for each agent in seconds
tx_amount_min = 1 # Minimum amount of satoshies in each transaction
tx_amount_max = 1 # Maximum amount of satoshies in each transaction
tx_max_route_tries = 10 # Maximum number of attempts to find a route for a transaction
routing_algorithm = "shortest_path" # ["shortest_path", "transparent"] # TODO: separate transparency and routing algorithm
