[simulation]
num_of_rounds = 1 # Number of runs of the simulation, statistics will be averaged over all runs, rounds run concurrently
num_of_agents = 100 # They work concurrently

[logging]
enabled = false # Enable logging

[network]
# You can use an exact number to reproduce the psoudo random results
seed = 1677085608
# All topologies will be connected with no self-loops
# ["random", "star", "complete"]
# IDEA: add reading network topology from a file
topology = "random"
nodes_num = 10000
channels_num = 70000
sats_min = 300000 # Minimum amount of satoshies in each side of the channel
sats_max = 3000000 # Maximum amount of satoshies in each side of the channel
reopen = false # Reopen closed channels 50-50, # TODO: Reopens channels of the first route tried, maybe not the best idea, but it is kinda similar to reality

[agents]
seed = 1677085608
check_source_balance = true # Only choose source nodes with enough balance, set this to false only if reopening is enabled
num_of_transactions = 200 # Total number of transactions a single agent will make
tx_rest = 0 # Delay between transactions for each agent in seconds
tx_amount_min = 100000 # Minimum amount of satoshies in each transaction
tx_amount_max = 1000000 # Maximum amount of satoshies in each transaction
tx_max_route_tries = 10 # Maximum number of attempts to find a route for a transaction
routing_algorithm = "shortest_path" # ["BFS"]
