[network]
# You can use an exact number to reproduce the psoudo random results
seed = 1677085608
# All topologies will be strictly connected with no self-loops
# ["random", "star", "complete"]
# IDEA: add reading network topology from a file
topology = "random"
nodes_num = 3
channels_num = 3
sats_min = 100 # Minimum amount of satoshies in each side of the channel
sats_max = 100000 # Maximum amount of satoshies in each side of the channel

[agents]
seed = 1677085608
num_of_agents = 5 # They work concurrently
tx_delay = 1 # Delay between transactions for each agent in seconds
tx_amount_min = 1
tx_amount_max = 10

[routing]
algorithm = "BFS" # ["BFS"]
